name: eGPT GRPC Continuous Integration

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
jobs:
  build_and_push_to_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install protobuf-compiler
      - name: Build Lint
        run: cargo clippy

      - name: Build
        run: |
          cargo build --verbose

      - name: Build Docker image
        run: |
          docker build -t eddique/egpt-grpc .
          docker tag eddique/egpt-grpc eddique/egpt-grpc:latest
      
      - name: Push to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push eddique/egpt-grpc:latest